version: "3.8"

services:
  oss_database:
    image: bitnami/postgres:latest
    container_name: oss_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: galantixa
      POSTGRES_DB: postgres
    volumes:
      - "oss_postgresql_data:/var/lib/postgresql/data"
    networks:
      - ossnetwork
    ports:
      - "5432:5432"
    restart: always

  oss_nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx_oss
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/sites-enabled"
    depends_on:
      - oss_express
    restart: always
    networks:
      - ossnetwork

  oss_express:
    build:
      context: ./express
      dockerfile: dockerfile
    container_name: oss_express
    ports:
      - "5000:5000"
    depends_on:
      - oss_database
    restart: always
    networks:
      - ossnetwork

networks:
  ossnetwork:
    driver: bridge

volumes:
  oss_postgresql_data:
