version: "3.8"

services:
  oss_database:
    image: "postgres:latest"
    container_name: osspostgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: galantixa
      POSTGRES_DB: postgres
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    networks:
      - ossnetwork
    ports:
      - "5432:5432"
    restart: unless-stopped

  oss_nginx:
    build:
      context: /nginx
      dockerfile: Dockerfile
    container_name: nginxoss
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/sites-enabled"
    depends_on:
      - ossexpress
    restart: unless-stopped
    networks:
      - ossnetwork

  oss_express:
    build:
      context: ./express
      dockerfile: dockerfile
    container_name: ossexpress
    ports:
      - "5000:5000"
    depends_on:
      - ossDatabase
    restart: unless-stopped
    networks:
      - ossnetwork

networks:
  ossnetwork:
